name: CI

on:
  pull_request:
    branches:
      - staging
      - main
  push:
    branches:
      - staging

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run lint -- --max-warnings 9999
      - run: npm run build
